import mongoose from 'mongoose';
import { logger } from '../../../logger/index.js';
import { SyncEventModel } from '../../../database/models/SyncEvent.js';
import { SyncStateModel } from '../../../database/models/SyncState.js';
import { redisClient } from '../../../redis/connection.js';
import type { SyncEvent, SyncResponse, SyncEventType } from '@shared/types/sync.js';

const SYNC_EVENT_TTL_DAYS = 7;

// ---------------------------------------------------------------------------
// Counter for monotonically increasing version numbers per user
// ---------------------------------------------------------------------------

async function nextVersion(userId: string): Promise<number> {
  try {
    const key = `sync:version:${userId}`;
    const version = await redisClient.incr(key);
    return version;
  } catch {
    // Fallback to timestamp if Redis is down
    return Date.now();
  }
}

// ---------------------------------------------------------------------------
// SyncService
// ---------------------------------------------------------------------------

export class SyncService {
  async emitEvent(
    userId: string,
    deviceId: string,
    type: SyncEventType,
    payload: Record<string, unknown>,
  ): Promise<void> {
    try {
      const version = await nextVersion(userId);
      const expiresAt = new Date(Date.now() + SYNC_EVENT_TTL_DAYS * 24 * 60 * 60 * 1000);

      await SyncEventModel.create({
        userId: new mongoose.Types.ObjectId(userId),
        deviceId,
        type,
        payload,
        version,
        processedBy: [],
        expiresAt,
      });
    } catch (err) {
      logger.warn('[SyncService] Failed to emit sync event', {
        userId,
        type,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  async pull(
    userId: string,
    deviceId: string,
    lastVersion: number,
    limit = 100,
  ): Promise<SyncResponse> {
    const userOid = new mongoose.Types.ObjectId(userId);

    const events = await SyncEventModel.find({
      userId: userOid,
      version: { $gt: lastVersion },
      // Exclude events generated by this device (no need to sync your own)
      deviceId: { $ne: deviceId },
    })
      .sort({ version: 1 })
      .limit(limit + 1)
      .lean()
      .exec();

    const hasMore = events.length > limit;
    const pageEvents = events.slice(0, limit);

    let currentVersion = lastVersion;
    const result: SyncEvent[] = pageEvents.map((e) => {
      if (e.version > currentVersion) currentVersion = e.version;
      return {
        id: e._id.toString(),
        type: e.type,
        userId: e.userId.toString(),
        deviceId: e.deviceId,
        payload: e.payload,
        version: e.version,
        timestamp: (e.createdAt as Date).toISOString(),
      };
    });

    // Update sync state for this device
    await this.updateSyncState(userId, deviceId, currentVersion);

    return { events: result, currentVersion, hasMore };
  }

  async getSyncState(userId: string, deviceId: string) {
    const userOid = new mongoose.Types.ObjectId(userId);
    const state = await SyncStateModel.findOne({ userId: userOid, deviceId }).lean().exec();

    return {
      userId,
      deviceId,
      lastSyncVersion: state?.lastSyncVersion ?? 0,
      lastSyncAt: (state?.lastSyncAt ?? new Date()).toISOString(),
    };
  }

  private async updateSyncState(
    userId: string,
    deviceId: string,
    version: number,
  ): Promise<void> {
    await SyncStateModel.findOneAndUpdate(
      {
        userId: new mongoose.Types.ObjectId(userId),
        deviceId,
      },
      {
        $set: { lastSyncVersion: version, lastSyncAt: new Date() },
      },
      { upsert: true },
    ).exec();
  }

  async acknowledge(userId: string, deviceId: string, version: number): Promise<void> {
    await this.updateSyncState(userId, deviceId, version);
  }
}

export const syncService = new SyncService();
